jobs:
- job: BuildLinuxWithSonarQube
  displayName: Build for Linux\Autotools With SonarQube
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # Make Build Wrapper available
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'azure-sq' # Name of the SonarQube service endpoint you created
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: "sonar.cfamily.build-wrapper-output=build_wrapper_output_directory"
  - bash: |
      mkdir -p $HOME/.sonar
      # Replace <SONARQUBE_HOST_URL> with your SonarQube server URL
      curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip 'http://f0348431025e.ngrok.io/static/cpp/build-wrapper-linux-x86.zip'
      unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
    displayName: Download and install build wrapper
  - bash: |
      mkdir build
      cmake -S . -B build
      export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
      build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory cmake --build build/ --config Release
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarQubeAnalyze@4
